### ISSUE TITLE
[anctree_hi] warnings on htrees with sosa > 1 000

### ISSUE THREAD

**Issue by a2line** [a2line/geneweb#2]
File "anctree.txt", line 206, characters 44-61:
Failed - num value expected
Found = 1 002

File "anctree.txt", line 206, characters 44-61:
Failed - num value expected
Found = 1 004

File "anctree.txt", line 206, characters 44-61:
Failed - num value expected
Found = 1 006

**Comment by gwmr** [comment]
https://github.com/a2line/geneweb/blob/sosahtree/hd/etc/templm/anctree_hi.txt#L147

**Comment by hgouraud** [comment]
Peux tu me dire la configuration exacte qui provoque cette erreur.
J’ai des ancêtres en pagaille dans la base de régression (sosa 4 096) mais je ne vois pas l’erreur!
? arbre en I, avec N° sosa ?

Henri
------

**Comment by a2line** [comment]
Je les vois pour les h et i-trees par couple à plus de 10 générations. Je soupçonne le séparateur des milliers qui apparait sur ancestor.interval qui ferait que l’entier n’est plus reconnu comme un chiffre ?!
